spring:
  datasource:
    url: jdbc:postgresql://110.43.51.23:5432/demo
    data-username: postgres
    data-password: 123456
    driver-class-name: org.postgresql.Driver
    platform: postgres
server:
  port: 9220

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


